import { NextResponse } from 'next/server';
import { kv } from '@vercel/kv';
import { validateSession } from '../../../lib/auth.js';
import { writeAudit } from '../../../lib/audit.js';

export const dynamic = 'force-dynamic';

const KEY = 'nc:kpi:outreach';
const LIST_TYPES = ['Pre-Foreclosure', 'Vacant', 'Tired Landlords', 'Probate', 'Tax Delinquent', 'Other'];

function clean(v) {
  return typeof v === 'string' ? v.trim() : '';
}

function parseCounties(raw) {
  if (Array.isArray(raw)) return raw.map(c => String(c).trim()).filter(Boolean);
  if (typeof raw === 'string') return raw.split(',').map(s => s.trim()).filter(Boolean);
  return [];
}

export async function GET(request) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const list = (await kv.get(KEY)) || [];
  return NextResponse.json(list.filter(e => !e.deleted));
}

export async function POST(request) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const body = await request.json();

  const textsSent = Math.max(0, parseInt(String(body.textsSent || '').replace(/[^0-9]/g, '')) || 0);

  const entry = {
    id: Date.now().toString(),
    listName: clean(body.listName),
    counties: parseCounties(body.counties),
    listType: LIST_TYPES.includes(body.listType) ? body.listType : 'Other',
    campaignId: body.campaignId || null,
    contacts: Number(body.contacts) || 0,
    textsSent,
    status: body.status === 'Complete' ? 'Complete' : 'Active',
    date: clean(body.date),
    createdBy: session.userName,
    createdAt: new Date().toISOString(),
    deleted: false,
  };

  const list = (await kv.get(KEY)) || [];
  list.push(entry);
  await kv.set(KEY, list);

  /* Auto-deduct SMS cost from marketing balance when textsSent > 0 */
  if (textsSent > 0) {
    const settings = (await kv.get('nc:kpi:settings')) || {};
    const costPerText = typeof settings.smsCostPerText === 'number' ? settings.smsCostPerText : 0.04;
    const smsCost = parseFloat((textsSent * costPerText).toFixed(2));

    if (smsCost > 0) {
      const balances = (await kv.get('nc:expenses:manual_balances')) || {};
      if (balances.marketing != null) {
        balances.marketing = Math.max(0, (balances.marketing || 0) - smsCost);
        await kv.set('nc:expenses:manual_balances', balances);
      }

      const expenseRaw = (await kv.get('nc:expenses:entries'));
      const expenses = Array.isArray(expenseRaw) ? expenseRaw : [];
      expenses.push({
        id: Date.now().toString() + '_sms',
        date: entry.date || new Date().toISOString().slice(0, 10),
        vendor: 'SMS — ' + (entry.listName || 'Campaign'),
        amount: smsCost,
        account: 'marketing',
        type: 'auto-sms',
        notes: `Auto: ${textsSent} texts \xd7 $${costPerText.toFixed(4)}`,
        loggedBy: session.userName,
        loggedAt: new Date().toISOString(),
        deleted: false,
        autoGenerated: true,
        outreachEntryId: entry.id,
      });
      await kv.set('nc:expenses:entries', expenses);
    }
  }

  await writeAudit(session.userId, session.userName, 'novora-capital', 'OUTREACH_CREATED', `List: ${entry.listName}, Type: ${entry.listType}, TextsSent: ${textsSent}`);
  return NextResponse.json(entry);
}
