import { NextResponse } from 'next/server';
import { kv } from '@vercel/kv';
import { validateSession } from '../../../lib/auth.js';
import { writeAudit } from '../../../lib/audit.js';

export const dynamic = 'force-dynamic';

const KEY = 'nc:kpi:sms';
const SETTINGS_KEY = 'nc:kpi:settings';

export async function GET(request) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const list = (await kv.get(KEY)) || [];
  return NextResponse.json(list.filter(e => !e.deleted));
}

export async function POST(request) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const body = await request.json();

  const date = typeof body.date === 'string' ? body.date.trim() : '';
  const campaignId = body.campaignId || null;

  // Duplicate check: same date → return existingId so UI can switch to edit mode
  const existing = (await kv.get(KEY)) || [];
  const dup = existing.find(e => !e.deleted && e.date === date);
  if (dup) return NextResponse.json({ error: 'Duplicate SMS entry for this date', existingId: dup.id }, { status: 409 });

  const settings = (await kv.get(SETTINGS_KEY)) || {};
  const smsCostPerText = typeof settings.smsCostPerText === 'number' ? settings.smsCostPerText : 0.04;
  const sentCount = Number(body.sent) || 0;
  const smsCost = Math.round(sentCount * smsCostPerText * 100) / 100;

  const entry = {
    id: Date.now().toString(),
    date,
    sent: sentCount,
    positiveReplies: Number(body.positiveReplies) || 0,
    wantsToSell: Number(body.wantsToSell) || 0,
    qualified: Number(body.qualified) || 0,
    offers: Number(body.offers) || 0,
    contracts: Number(body.contracts) || 0,
    campaignId,
    smsCost,
    loggedBy: session.userName,
    loggedAt: new Date().toISOString(),
    deleted: false,
  };

  const list = (await kv.get(KEY)) || [];
  list.push(entry);
  await kv.set(KEY, list);

  // Auto-deduct SMS cost from marketing balance & create expense entry
  if (smsCost > 0) {
    const balances = (await kv.get('nc:expenses:manual_balances')) || {};
    balances.marketing = (typeof balances.marketing === 'number' ? balances.marketing : 0) - smsCost;
    await kv.set('nc:expenses:manual_balances', balances);

    const expEntries = (await kv.get('nc:expenses:entries')) || [];
    expEntries.push({
      id: Date.now().toString() + '_sms',
      account: 'marketing',
      vendor: 'AUTO — SMS',
      amount: smsCost,
      category: 'SMS Marketing',
      date: entry.date || new Date().toISOString().slice(0, 10),
      notes: `Auto SMS cost: ${sentCount} texts \xd7 $${smsCostPerText}`,
      type: 'auto-sms',
      autoGenerated: true,
      smsEntryId: entry.id,
      loggedBy: session.userName,
      loggedAt: new Date().toISOString(),
      deleted: false,
    });
    await kv.set('nc:expenses:entries', expEntries);
  }

  await writeAudit(session.userId, session.userName, 'novora-capital', 'SMS_LOGGED', `Date: ${date}, Sent: ${sentCount}`);
  return NextResponse.json(entry);
}
