import { NextResponse } from 'next/server';
import { kv } from '@vercel/kv';
import { validateSession } from '../../../../lib/auth.js';
import { writeAudit } from '../../../../lib/audit.js';

export const dynamic = 'force-dynamic';

const KEY = 'nc:kpi:sms';
const SETTINGS_KEY = 'nc:kpi:settings';
const FIELDS = ['sent', 'positiveReplies', 'wantsToSell', 'qualified', 'offers', 'contracts'];

export async function PUT(request, { params }) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const body = await request.json();

  const list = (await kv.get(KEY)) || [];
  const idx = list.findIndex(e => e.id === params.id);
  if (idx === -1) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const oldEntry = list[idx];
  const oldSent = oldEntry.sent || 0;

  const updates = {};
  for (const f of FIELDS) {
    if (body[f] !== undefined) updates[f] = Number(body[f]) || 0;
  }
  if (body.campaignId !== undefined) updates.campaignId = body.campaignId || null;
  if (body.date !== undefined) updates.date = typeof body.date === 'string' ? body.date.trim() : '';

  const newSent = updates.sent !== undefined ? updates.sent : oldSent;
  const sentDiff = newSent - oldSent;

  if (sentDiff !== 0) {
    const settings = (await kv.get(SETTINGS_KEY)) || {};
    const smsCostPerText = typeof settings.smsCostPerText === 'number' ? settings.smsCostPerText : 0.04;
    const costDiff = Math.round(sentDiff * smsCostPerText * 100) / 100;

    const balances = (await kv.get('nc:expenses:manual_balances')) || {};
    balances.marketing = (typeof balances.marketing === 'number' ? balances.marketing : 0) - costDiff;
    await kv.set('nc:expenses:manual_balances', balances);

    const newCost = Math.round(newSent * smsCostPerText * 100) / 100;
    updates.smsCost = newCost;

    // Update linked auto expense entry
    const expEntries = (await kv.get('nc:expenses:entries')) || [];
    const autoIdx = expEntries.findIndex(e => e.smsEntryId === params.id && e.autoGenerated && !e.deleted);
    if (autoIdx !== -1) {
      expEntries[autoIdx] = {
        ...expEntries[autoIdx],
        amount: newCost,
        notes: `Auto SMS cost: ${newSent} texts \xd7 $${smsCostPerText}`,
      };
      await kv.set('nc:expenses:entries', expEntries);
    }
  }

  list[idx] = { ...list[idx], ...updates, updatedAt: new Date().toISOString() };
  await kv.set(KEY, list);
  await writeAudit(session.userId, session.userName, 'novora-capital', 'SMS_UPDATED', params.id);
  return NextResponse.json(list[idx]);
}

export async function DELETE(request, { params }) {
  const session = await validateSession(request.cookies.get('novora_session')?.value);
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const list = (await kv.get(KEY)) || [];
  const idx = list.findIndex(e => e.id === params.id);
  if (idx === -1) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const entry = list[idx];
  const oldSent = entry.sent || 0;

  if (oldSent > 0) {
    const settings = (await kv.get(SETTINGS_KEY)) || {};
    const smsCostPerText = typeof settings.smsCostPerText === 'number' ? settings.smsCostPerText : 0.04;
    const costToReverse = Math.round(oldSent * smsCostPerText * 100) / 100;

    const balances = (await kv.get('nc:expenses:manual_balances')) || {};
    balances.marketing = (typeof balances.marketing === 'number' ? balances.marketing : 0) + costToReverse;
    await kv.set('nc:expenses:manual_balances', balances);

    // Mark linked auto expense as deleted
    const expEntries = (await kv.get('nc:expenses:entries')) || [];
    const autoIdx = expEntries.findIndex(e => e.smsEntryId === params.id && e.autoGenerated && !e.deleted);
    if (autoIdx !== -1) {
      expEntries[autoIdx] = { ...expEntries[autoIdx], deleted: true, deletedAt: new Date().toISOString() };
      await kv.set('nc:expenses:entries', expEntries);
    }
  }

  list[idx] = { ...list[idx], deleted: true, deletedAt: new Date().toISOString() };
  await kv.set(KEY, list);
  await writeAudit(session.userId, session.userName, 'novora-capital', 'SMS_DELETED', params.id);
  return NextResponse.json({ success: true });
}
